### ISSUE TITLE
[REPOSITORY] Caching Repository connector

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-connector-omrs-caching#10]
### Name

egeria-connector-omrs-caching

### Owner

davidradl

### Deliverable

Provides an OMRS repository proxy connector that has an embedded repository that can be used to cache entities and relationships. This is useful when running an adapter that uses an event mapper to poll a 3rd party technology; and then writes its content to this connector. This connector services queries by paaing them to the imbedded repository connector   

### Build, test and CI-CD process

Gradle
Java
usual checks

### Dependencies

only depends on core Egeria artifacts

### Justification

This is a technology independent connector that as detailed in [https://github.com/odpi/egeria/pull/6999](https://github.com/odpi/egeria/pull/6999). The TLC and code owners advised this be in a new repo on the 19th of October,

### Assumptions

Yes all true

### Work Plan

Before creating the repo
- [x] review overall request & get clarifications
- [x] get approval on developer/TSC call from maintainers

Creating the repo
- [x] Create the repo under the odpi organization (default gitignore, license, readme)
- [x] Setup branch protection rules
- [x] Set pull request options (allow merge, squash, rebase, suggest updating, allow automerge, do not delete head)
- [x] Update security settings in repo (policy, advisories, alerts)
- [x] set up permissions

First steps
- [x] Initial code-drop (author)

Getting CI/CD started & refining settings
- [x] Add initial build script for PR (including gradle wrapper if required)
- [x] Add initial build script for merge

Further Refinement
- [x] Add link in egeria docs to new repo describing purpose ( https://github.com/odpi/egeria-docs/blob/main/site/docs/education/tutorials/git-and-git-hub-tutorial/egeria-git-repositories.md ) 
- [x] Add to connector catalog, if new repo is for connector ( https://github.com/odpi/egeria-docs/blob/main/site/docs/connectors/index.md )
- [ ] Add to release process docs ( https://github.com/odpi/egeria-docs/blob/main/site/docs/guides/contributor/release-process/index.md )
- [x] Add required credentials for publishing to container repos, maven central etc
- [x] Add artifact signing if needed
- [x] Add dependabot config        
- [x] Add CodeQL 
- [ ] Add to LFX ( https://projectadmin.lfx.linuxfoundation.org/project/a092M00001IV4JtQAL  ) for
  - [ ] LFXSecurity
  - [ ] LFAnalytics
- [ ] Add check for stale defects
- [ ] Add any required issue tags

Release
- [ ] Add release pipeline

**Comment by davidradl** [comment]
@planetf1 thanks - I have put up the initial code -  it did not look like the pr compiled the code - did I miss that?

**Comment by planetf1** [comment]
The last build seemed to build ok ? -> https://github.com/odpi/egeria-connector-omrs-caching/actions/runs/3289559311

**Comment by davidradl** [comment]
I do not intend to document or release this at this time, until this is asked for by members of the community.
